---
sudo: required
language: python
python: 3.6

env:
  global:
    - secure: nreNYK6qyBBxdp2JKZ4ZsxEfbvuu0MkXzC2mg5AxqDEw98gdKywdQz+6OXG1gYneL8fnl/2VEePtowq9XqUR/9K7u9UCjvqx+vQcgZ+DrETlkU8sMvlk4f3pkgCwsZiFRXeb2/PaH9gK8l2WklQ+Xp7aVZvUbdaPG0uATlItQc1piEfGqgVboD1dxETF6xFoQX45QJRZf/5qmujHjmo3LLfLx2gRR/Lhl8Po86fh03r+vrn5iJTj4OscN7Av7ApMD7gnMBNa2FLYpSfHSSwTP0/T6B8iplmZUn/Ll8JR+J2c4gAFbWxYwssHb5L6u9nLJYdrNAWd4XA9+xlsZVMULN+jLGp4e13lzNlVq6ZdA2eICc0IgWg0hgdCOHERt2j9i7emU8xKI5PwEsYG8ghjK1hgYHfWlfq4fk9HBSFoxFDL5YxrwhB7rL8BKNQPp8fOxbinPTpTRyUNXLs17iZiOmpYm2QdzI2KYY6vPaEkIjwKlKTu58rXLrasAFvG0NK/ivxkvezh6JCnHW4UiAZRLQ1gj3kdgnxZ9mL8uhWmt7nZyNcnYQRilGIATZrUaahReeoFN6lqm2/rDRvSasg8JgSrkpFwafbzMD9YrkqgvotXVixVn3v8Xkud8vSn33BeMFaxFHKdPrWa3m9nxz7DcJE+Vzq9LK1EMgBMY6YwO0w=

install:
  - sudo apt-get update
  - sudo update-ca-certificates
  - gem install bundler
  - bundle install
  - bundle update

script:
  # Check website
  - |
    set -e
    yamllint .
    bundle exec jekyll build

after_success:
  - |
    if [ "$TRAVIS_PULL_REQUEST" == "false" -a "$TRAVIS_BRANCH" == "master" ]
    then
      bin/publish
    fi
